--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/esh123cookie/IdkFactionsCore
build-by-default: true
branches:
- master
projects:
  IdkFactionsCore:
    path: ""
    lint:
      phpstan: false
...
